### ISSUE TITLE
Docker build didn't work

### ISSUE THREAD

**Issue by curlup** [pughlab/ctims#47]
Disclaimer: I have zero understanding what I should be doing

but

I ran `docker build .` and it fails for me on some NX stuff for which googling didn't help, so here's the trace

```
$ docker build .
[+] Building 93.4s (11/15)
 => [internal] load build definition from Dockerfile                                                                  0.0s
 => => transferring dockerfile: 1.03kB                                                                                0.0s
 => [internal] load .dockerignore                                                                                     0.0s
 => => transferring context: 34B                                                                                      0.0s
 => [internal] load metadata for docker.io/library/node:current-alpine3.16                                            0.4s
 => [base 1/5] FROM docker.io/library/node:current-alpine3.16@sha256:f9b54b46639a9017b39eba677cf44c8cb96760ca69dadcc  0.0s
 => [internal] load build context                                                                                     0.0s
 => => transferring context: 32.80kB                                                                                  0.0s
 => CACHED [base 2/5] RUN apk add --update python3 make g++ && rm -rf /var/cache/apk/*                                0.0s
 => CACHED [base 3/5] WORKDIR /app                                                                                    0.0s
 => CACHED [base 4/5] COPY ./package.json ./yarn.* ./                                                                 0.0s
 => CACHED [base 5/5] RUN yarn install --pure-lockfile                                                                0.0s
 => [build 1/2] COPY . .                                                                                              0.1s
 => ERROR [build 2/2] RUN npx nx build web --verbose                                                                 92.8s
------
 > [build 2/2] RUN npx nx build web --verbose:
#9 1.347
#9 1.348  >  NX   workspace.json is ignored
#9 1.348
#9 1.348    Nx no longer reads configuration from workspace.json.
#9 1.348    Run "nx g @nrwl/workspace:fix-configuration" to split workspace.json into individual project.json files.
#9 1.348
#9 6.636
#9 6.636 > nx run web:build:production
#9 6.636
#9 9.022 Attention: Next.js now collects completely anonymous telemetry regarding usage.
#9 9.023 This information is used to shape Next.js' roadmap and prioritize features.
#9 9.023 You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
#9 9.023 https://nextjs.org/telemetry
#9 9.023
#9 9.195 info  - Skipping linting
#9 9.196 info  - Checking validity of types...
#9 23.27 info  - Creating an optimized production build...
#9 24.15 Browserslist: caniuse-lite is outdated. Please run:
#9 24.15   npx browserslist@latest --update-db
#9 24.15   Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
#9 26.34 Browserslist: caniuse-lite is outdated. Please run:
#9 26.34   npx browserslist@latest --update-db
#9 26.34   Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
#9 91.11 info  - Compiled successfully
#9 91.12 info  - Collecting page data...
#9 92.41 TypeError [ERR_INVALID_URL]: Invalid URL
#9 92.41     at new NodeError (node:internal/errors:399:5)
#9 92.41     at new URL (node:internal/url:743:13)
#9 92.41     at parseUrl (/app/node_modules/next-auth/utils/parse-url.js:17:16)
#9 92.41     at Object.<anonymous> (/app/node_modules/next-auth/react/index.js:72:34)
#9 92.41     at Module._compile (node:internal/modules/cjs/loader:1255:14)
#9 92.41     at Module._extensions..js (node:internal/modules/cjs/loader:1309:10)
#9 92.41     at Module.load (node:internal/modules/cjs/loader:1113:32)
#9 92.41     at Module._load (node:internal/modules/cjs/loader:960:12)
#9 92.41     at Module.require (node:internal/modules/cjs/loader:1137:19)
#9 92.41     at require (node:internal/modules/helpers:121:18) {
#9 92.41   input: '',
#9 92.41   code: 'ERR_INVALID_URL'
#9 92.41 }
#9 92.41
#9 92.41  >  NX   Failed to collect page data for /trials/create
#9 92.41
#9 92.41
#9 92.41 Error: Failed to collect page data for /trials/create
#9 92.41     at /app/node_modules/next/dist/build/utils.js:949:15
#9 92.41     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
#9 92.57
#9 92.57
#9 92.57
#9 92.57  >  NX   Running target build for project web failed
#9 92.58
#9 92.58    Failed tasks:
#9 92.58
#9 92.58    - web:build:production
#9 92.58
#9 92.58    Hint: run the command with --verbose for more details.
#9 92.58
#9 92.60 npm notice
#9 92.60 npm notice New minor version of npm available! 9.6.6 -> 9.7.1
#9 92.60 npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.7.1>
#9 92.60 npm notice Run `npm install -g npm@9.7.1` to update!
#9 92.60 npm notice
------
executor failed running [/bin/sh -c npx nx build web --verbose]: exit code: 1
``` 

Any direction would be appreciated

**Comment by jagnathan** [comment]
Readme is under internal review process. Readme will be updated after review is complete.
